import { FormEvent, useEffect, useState } from 'react';
import { Boxes, ChevronDown, Pencil, Plus, Store, Tags, Truck, Users } from 'lucide-react';
import { useNavigate } from 'react-router-dom';
import { Toast } from '../components/Toast';
import { getBatches, getCategories, getProducts, getSellerInventory, getSellers, getSuppliers } from '../lib/data';
import { money } from '../lib/format';
import { supabase } from '../lib/supabase';
import type { Category, InventoryBatch, Product, Seller, SellerInventory, Supplier } from '../types';
import { Top } from './Products';
type Section = 'categories' | 'suppliers' | 'sellers';
export function Management() {
  const nav = useNavigate(); const [section, setSection] = useState<Section>('categories');
  const [categories, setCategories] = useState<Category[]>([]); const [suppliers, setSuppliers] = useState<Supplier[]>([]); const [sellers, setSellers] = useState<Seller[]>([]);
  const [products, setProducts] = useState<Product[]>([]); const [batches, setBatches] = useState<InventoryBatch[]>([]); const [inventory, setInventory] = useState<SellerInventory[]>([]);
  const [name, setName] = useState(''); const [editing, setEditing] = useState<{ id: string } | null>(null); const [msg, setMsg] = useState('');
  const [sellerId, setSellerId] = useState(''); const [productId, setProductId] = useState(''); const [quantity, setQuantity] = useState(''); const [direction, setDirection] = useState<'to_seller' | 'to_central'>('to_seller');
  const load = async () => { const [c, s, v, p, b, i] = await Promise.all([getCategories(), getSuppliers(), getSellers(), getProducts(true), getBatches(), getSellerInventory()]); setCategories(c); setSuppliers(s); setSellers(v); setProducts(p); setBatches(b); setInventory(i); };
  useEffect(() => { void load(); }, []);
  async function save(e: FormEvent) { e.preventDefault(); const table = section === 'categories' ? 'product_categories' : section; const payload = { name: name.trim() }; const result = editing ? await supabase.from(table).update(payload).eq('id', editing.id) : section === 'sellers' ? await supabase.from('sellers').insert({ ...payload, sort_order: sellers.length + 1 }) : await supabase.from(table).insert(payload); if (result.error) setMsg(result.error.message); else { setMsg(editing ? 'Nome atualizado.' : 'Cadastro criado.'); setName(''); setEditing(null); await load(); } }
  function edit(item: Category | Supplier | Seller) { setEditing({ id: item.id }); setName(item.name); }
  async function transfer(e: FormEvent) { e.preventDefault(); const { error } = await supabase.rpc('transfer_seller_stock', { p_seller_id: sellerId, p_product_id: productId, p_quantity: Number(quantity), p_direction: direction, p_notes: null }); if (error) setMsg(error.message); else { setMsg(direction === 'to_seller' ? 'Estoque enviado ao vendedor.' : 'Estoque devolvido ao central.'); setQuantity(''); await load(); } }
  const additional = sellers.filter(s => !s.is_primary);
  return <div><Top title="Organização" back={() => nav(-1)} /><p className="mt-2 text-sm text-muted">Categorias, fornecedores e vendedores do seu negócio.</p>
    <div className="mt-5 grid grid-cols-3 gap-2"><Tab active={section === 'categories'} onClick={() => change('categories')} icon={<Tags size={17} />} text="Categorias" /><Tab active={section === 'suppliers'} onClick={() => change('suppliers')} icon={<Truck size={17} />} text="Fornecedores" /><Tab active={section === 'sellers'} onClick={() => change('sellers')} icon={<Users size={17} />} text="Vendedores" /></div>
    <form onSubmit={save} className="card mt-4 flex gap-2 p-4"><input className="input min-w-0 flex-1" required value={name} onChange={e => setName(e.target.value)} placeholder={section === 'categories' ? 'Nome da categoria' : section === 'suppliers' ? 'Nome do fornecedor' : `Vendedor ${sellers.length + 1}`} /><button className="grid h-12 w-12 shrink-0 place-items-center rounded-xl bg-electric" aria-label="Salvar"><Plus /></button></form>
    <div className="mt-4 space-y-2">{section === 'categories' && categories.map(x => <Item key={x.id} title={x.name} subtitle={`${products.filter(p => p.category_id === x.id).length} produtos`} onEdit={() => edit(x)} />)}{section === 'suppliers' && suppliers.map(x => <SupplierItem key={x.id} supplier={x} batches={batches} onEdit={() => edit(x)} />)}{section === 'sellers' && sellers.map(x => <Item key={x.id} title={x.name} subtitle={x.is_primary ? 'Vendedor principal · estoque central' : `${inventory.filter(i => i.seller_id === x.id).reduce((n, i) => n + i.quantity, 0)} unidades em posse`} onEdit={() => edit(x)} />)}</div>
    {section === 'sellers' && additional.length > 0 && <form onSubmit={transfer} className="card mt-5 space-y-4 p-5"><h2 className="flex items-center gap-2 font-bold"><Boxes className="text-cyan" size={20} />Transferir estoque</h2><p className="text-sm text-muted">Envie produtos ao vendedor ou devolva unidades ao estoque central.</p><Select label="Vendedor" value={sellerId} set={setSellerId} options={additional.map(x => [x.id, x.name])} /><Select label="Produto" value={productId} set={setProductId} options={products.map(x => [x.id, `${x.name} · central ${x.current_stock}`])} /><div className="grid grid-cols-2 gap-3"><label><span className="label">Movimento</span><select className="input" value={direction} onChange={e => setDirection(e.target.value as typeof direction)}><option value="to_seller">Enviar</option><option value="to_central">Devolver</option></select></label><label><span className="label">Quantidade</span><input className="input" type="number" min="1" required value={quantity} onChange={e => setQuantity(e.target.value)} /></label></div><button className="btn-primary w-full">Confirmar transferência</button></form>}
    {section === 'sellers' && !additional.length && <div className="card mt-5 p-5 text-sm text-muted">O fluxo continua simples enquanto existir somente o Vendedor principal. Cadastre outro vendedor para habilitar transferências e seleção nas vendas.</div>}{msg && <Toast message={msg} />}
  </div>;
  function change(next: Section) { setSection(next); setEditing(null); setName(''); }
}
function Tab({ active, onClick, icon, text }: { active: boolean; onClick: () => void; icon: React.ReactNode; text: string }) { return <button onClick={onClick} className={`chip flex items-center justify-center gap-1 px-1 ${active ? 'chip-active' : ''}`}>{icon}{text}</button>; }
function Item({ title, subtitle, onEdit }: { title: string; subtitle: string; onEdit: () => void }) { return <div className="card flex items-center gap-3 p-4"><Store size={19} className="text-cyan" /><div className="min-w-0 flex-1"><b>{title}</b><p className="text-xs text-muted">{subtitle}</p></div><button onClick={onEdit} className="grid h-10 w-10 place-items-center rounded-xl bg-white/[.05]"><Pencil size={17} /></button></div>; }
function SupplierItem({ supplier, batches, onEdit }: { supplier: Supplier; batches: InventoryBatch[]; onEdit: () => void }) { const own = batches.filter(b => b.supplier_id === supplier.id); const invested = own.flatMap(b => b.inventory_batch_items || []).reduce((n, i) => n + i.quantity * Number(i.unit_cost), 0); return <details className="card p-4"><summary className="flex cursor-pointer list-none items-center gap-3"><Truck size={19} className="text-cyan" /><div className="flex-1"><b>{supplier.name}</b><p className="text-xs text-muted">{own.length} lotes · {money(invested)} investidos</p></div><button onClick={e => { e.preventDefault(); onEdit(); }} className="grid h-10 w-10 place-items-center rounded-xl bg-white/[.05]"><Pencil size={17} /></button><ChevronDown size={17} /></summary><div className="mt-4 border-t border-white/10 pt-3 text-sm text-muted">{own.map(b => <p key={b.id}>Lote {String(b.batch_number).padStart(4, '0')} · {(b.inventory_batch_items || []).reduce((n, i) => n + i.quantity, 0)} unidades</p>)}{!own.length && <p>Nenhum lote associado.</p>}</div></details>; }
function Select({ label, value, set, options }: { label: string; value: string; set: (v: string) => void; options: string[][] }) { return <label><span className="label">{label}</span><select className="input" required value={value} onChange={e => set(e.target.value)}><option value="">Selecione</option>{options.map(([id, n]) => <option key={id} value={id}>{n}</option>)}</select></label>; }
