export type PaymentMethod='pix'|'cash'|'card'; export type SaleStatus='completed'|'cancelled';
export interface Category{id:string;user_id:string;name:string;active:boolean;created_at:string}
export interface Supplier{id:string;user_id:string;name:string;notes:string|null;active:boolean;created_at:string;updated_at:string}
export interface Seller{id:string;user_id:string;name:string;is_primary:boolean;active:boolean;sort_order:number;created_at:string;updated_at:string}
export interface SellerInventory{seller_id:string;product_id:string;quantity:number;products?:{name:string}}
export interface Product{id:string;user_id:string;category_id:string|null;active_batch_id?:string|null;name:string;description:string|null;unit_cost:number;sale_price:number;current_stock:number;minimum_stock:number|null;active:boolean;created_at:string;updated_at:string;product_categories?:{name:string}|null}
export interface SaleItem{id:string;sale_id:string;product_id:string;product_name:string;quantity:number;unit_price:number;unit_cost:number;subtotal:number;category_id?:string|null;category_name?:string|null;supplier_id?:string|null;supplier_name?:string|null;batch_id?:string|null}
export interface Sale{id:string;user_id:string;seller_id?:string|null;batch_id?:string|null;calculated_total:number;received_amount:number;payment_method:PaymentMethod;status:SaleStatus;created_at:string;cancelled_at:string|null;sale_items?:SaleItem[];sellers?:{name:string}|null}
export interface InventoryMovement{id:string;user_id:string;product_id:string;batch_id:string|null;movement_type:'entry'|'sale_out'|'positive_adjustment'|'negative_adjustment'|'sale_cancellation';quantity:number;unit_cost:number|null;reference_type:string|null;reference_id:string|null;notes:string|null;created_at:string;products?:{name:string}}
export interface InventoryBatch{id:string;user_id:string;supplier_id?:string|null;batch_number:number;notes:string|null;created_at:string;suppliers?:{name:string}|null;inventory_batch_items?:Array<{id:string;product_id:string;quantity:number;unit_cost:number;products?:{name:string}}>}
export interface DashboardStats{revenue:number;cost:number;grossProfit:number;salesCount:number;units:number;pix:number;cash:number;card:number;averageTicket:number}
